<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/06/18 14:03:49
sfConfig::add(array(
  'mod_cataloguewidget_enabled' => true,
  'mod_cataloguewidget_view_class' => 'sfPHP',
));
