<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/06/18 12:37:28
sfConfig::add(array(
  'mod_specimensearch_enabled' => true,
  'mod_specimensearch_view_class' => 'sfPHP',
));
