<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/06/18 14:03:48
sfConfig::add(array(
  'mod_cataloguewidgetview_enabled' => true,
  'mod_cataloguewidgetview_view_class' => 'sfPHP',
));
