<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/06/18 14:03:46
sfConfig::add(array(
  'mod_specimenwidgetview_enabled' => true,
  'mod_specimenwidgetview_view_class' => 'sfPHP',
));
