<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/06/18 12:45:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=darwin2',
  'username' => 'darwin2',
  'password' => 'darwin123',
  'name' => 'doctrine',
)),);
