<?php
// auto-generated by sfCacheConfigHandler
// date: 2020/06/18 14:39:41
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

