<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/06/18 14:39:44
sfConfig::add(array(
  'mod_specimensearchwidget_enabled' => true,
  'mod_specimensearchwidget_view_class' => 'sfPHP',
));
