<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/06/18 15:33:49
sfConfig::add(array(
  'mod_informativeworkflow_enabled' => true,
  'mod_informativeworkflow_view_class' => 'sfPHP',
));
